In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('BBCAfricaEye.csv')

In [5]:
df.head()

,tweet.created_at,tweet.text,tweet.lang,tweet.user.location,tweet.user.verified,tweet.source,tweet.retweet_count,tweet.favorite_count
0,2019-10-11 09:17:01,RT @kikimordi: Hey I forgot to mention that we...,en,NaN,False,Twitter for Android,143,0
1,2019-10-11 09:16:31,RT @TheAfricaReport: For Nigeria in particular...,en,"Abuja, Nigeria",False,Twitter for iPhone,3,0
2,2019-10-11 09:15:08,"RT @BBCAfrica: ""This was the hardest thing I'v...",en,Lagos Nigeria,False,Twitter for Android,130,0
3,2019-10-11 09:12:44,RT @TraQman: Locking up the ‘cold room’ is not...,en,NaN,False,Twitter for iPhone,7,0
4,2019-10-11 09:11:43,"RT @BBCAfrica: For the past year, BBC Africa E...",en,Kano,False,Twitter for iPad,16536,0

In [4]:
df.columns = ['tweet.created_at', 'tweet.text', 'tweet.lang', 'tweet.user.location', 'tweet.user.verified', 
              'tweet.source' , 'tweet.retweet_count','tweet.favorite_count']

In [6]:
df2 = pd.read_csv('ColdRoom.csv')

In [7]:
df2.columns = ['tweet.created_at', 'tweet.text', 'tweet.lang', 'tweet.user.location', 'tweet.user.verified', 
              'tweet.source' , 'tweet.retweet_count','tweet.favorite_count']

In [8]:
df2.head()

,tweet.created_at,tweet.text,tweet.lang,tweet.user.location,tweet.user.verified,tweet.source,tweet.retweet_count,tweet.favorite_count
0,2019-10-11 13:23:37,RT @Nwankpa_A: Not until there's a comprehensi...,en,Graceland,False,Twitter for iPhone,3,0
1,2019-10-11 13:16:27,RT @gidifeedtv: #SexForGrades #Coldroom https:...,und,OUTSIDE,False,Twitter for Android,1,0
2,2019-10-11 13:16:23,RT @gidifeedtv: #SexforGrades #Coldroom https:...,und,OUTSIDE,False,Twitter for Android,3,0
3,2019-10-11 13:16:09,RT @gidifeedtv: #SexforGrades #Coldroom cc @G...,und,OUTSIDE,False,Twitter for Android,1,0
4,2019-10-11 13:00:25,Nigerian Senate Reintroduces Anti-Sexual Haras...,en,Africa,True,allAfrica.com,0,1

In [9]:
df3 = pd.read_csv('DrBoniface.csv')

In [10]:
df3.columns = ['tweet.created_at', 'tweet.text', 'tweet.lang', 'tweet.user.location', 'tweet.user.verified', 
              'tweet.source' , 'tweet.retweet_count','tweet.favorite_count']

In [11]:
df3.head()

,tweet.created_at,tweet.text,tweet.lang,tweet.user.location,tweet.user.verified,tweet.source,tweet.retweet_count,tweet.favorite_count
0,2019-10-11 10:37:50,RT @Qweku_Jay: When the students refuse to ent...,en,"Tamale, Ghana",False,Twitter for iPhone,57,0
1,2019-10-11 08:09:44,RT @TWmagazineNG: Has another #UniLag lecturer...,en,NaN,False,Twitter for Android,1,0
2,2019-10-11 07:50:52,Has another #UniLag lecturer joined #DrBonifac...,en,"Lagos, Nigeria",False,Twitter for iPhone,1,2
3,2019-10-11 05:57:53,RT @ekekan12332: WOW I CAN'T BELIEVE I WON AGA...,en,NaN,False,Twitter for Android,3,0
4,2019-10-10 20:16:21,RT @therealveev: VERY CLEAN CAR FOR SALE\r\n20...,en,"Lagos, Nigeria",False,Twitter for Android,1,0

In [12]:
df4 = pd.read_csv('Gyampo.csv')

In [13]:
df4.columns = ['tweet.created_at', 'tweet.text', 'tweet.lang', 'tweet.user.location', 'tweet.user.verified', 
              'tweet.source' , 'tweet.retweet_count','tweet.favorite_count']

In [16]:
df5 = pd.read_csv('Sex4Grades.csv')
df6 = pd.read_csv('SexForGrades.csv')
df7 = pd.read_csv('Unilag.csv')

In [17]:
df5.columns = ['tweet.created_at', 'tweet.text', 'tweet.lang', 'tweet.user.location', 'tweet.user.verified', 
              'tweet.source' , 'tweet.retweet_count','tweet.favorite_count']
df6.columns = ['tweet.created_at', 'tweet.text', 'tweet.lang', 'tweet.user.location', 'tweet.user.verified', 
              'tweet.source' , 'tweet.retweet_count','tweet.favorite_count']
df7.columns = ['tweet.created_at', 'tweet.text', 'tweet.lang', 'tweet.user.location', 'tweet.user.verified', 
              'tweet.source' , 'tweet.retweet_count','tweet.favorite_count']

In [18]:
df7.head()

,tweet.created_at,tweet.text,tweet.lang,tweet.user.location,tweet.user.verified,tweet.source,tweet.retweet_count,tweet.favorite_count
0,2019-10-11 13:22:18,RT @micheal__og: Come join me tomorrow as I sp...,en,NaN,False,Twitter for iPhone,3,0
1,2019-10-11 13:12:46,RT @pweetychemmie: Please retweet my customers...,en,"Ilishan, Nigeria",False,Twitter Web App,2,0
2,2019-10-11 13:06:37,RT @micheal__og: Come join me tomorrow as I sp...,en,Nigeria,False,Twitter for Android,3,0
3,2019-10-11 12:28:17,RT @Mosmikey: We should not laugh.\r\nWe shoul...,en,"Tema, Ghana",False,Twitter for Android,4,0
4,2019-10-11 12:24:27,RT @Mosmikey: We should not laugh.\r\nWe shoul...,en,"Greater Accra, Ghana",False,Twitter for iPhone,4,0